# Generated by Django 4.0.1 on 2022-01-11 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mambotokea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='user.png', max_length=255, null=True),
        ),
    ]
